const data = {
  products: [
    {
      id: 1,
      title: "Veg. Samosa (vegan)",
      description: "Crispy Flour pastry with Potatoes and Peas. (2pcs).",
      price: "4.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 2,
      title: "Onion Bhaji (vegan)",
      description: "Onions, spinach, potatoes dipped in gram flour and fried.",
      price: "4.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 3,
      title: "Samosa Chat",
      description:
        "Vegetable pastry topped with chick peas, mint, onion, tamarind & yogurt (served cold).",
      price: "5.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 4,
      title: "Aaloo Aur Papri Chat",
      description:
        "Lentil wafers topped with potatoes, chick peas, yogurt, mint and tamarind (served cold)",
      price: "5.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 5,
      title: "Cashew Roll",
      description:
        "Cashew, potatoes, cheese mixed with green chillies and ginger and fried..",
      price: "6.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 6,
      title: "Chandrakala (vegan)",
      description:
        "White flour dumplings filled with dry fruits and fresh coconut and fried..",
      price: "5.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 7,
      title: "Aaloo Tikki",
      description:
        "Boiled potato, mixed with chick peas, green chillies and indian spices and fried..",
      price: "5.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 8,
      title: "Garlic Kabob",
      description:
        "Chicken breast marinated with garlic, sour cream herbs and spices baked in tandoor oven..",
      price: "6.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 9,
      title: "Malai Seek Kabob",
      description:
        "Minced Lamb marinated with onion, green chillies & baked in tandoor oven",
      price: "6.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 10,
      title: "Kali Mirch Ka Machhi",
      description:
        "Tilapia fish marinated with crushed black peppers, green chillies & fried.",
      price: "6.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 11,
      title: "Chicken Pakora",
      description:
        "Chicken Breast marinated with ginger, green chillies, gram flour & Indian Spices and fried..",
      price: "6.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 12,
      title: "Rasila Kabob",
      description:
        "Minced Chicken Breast marinated In ginger, green chillies and Indian Spices and baked in tandoor oven.",
      price: "6.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 13,
      title: "Chilli Chicken 65",
      description:
        "Chicken Breast fried with homemade Masala and sautéed with onion, ginger, garlic and hot chili powder.",
      price: "7.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 14,
      title: "Gobi Manchurian 65",
      description:
        "Batter fried Cauliflower chunks sautéed with onion, ginger and touch of garlic.",
      price: "7.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 15,
      title: "Paneer Tikka",
      description:
        "Cheese cube(paneer)onion, belpeppers marinated with indian spices and baked in tandoor oven.",
      price: "7.99",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 16,
      title: "Lamb Sekuwa",
      description:
        "Lamb cubes, fresh ginger, garlic, honey green chilli with marinated Nepali style & spices.",
      price: "10.99",
      countInStock: 10,
      category: "appetizer",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 17,
      title: "Chicken Sekuwa",
      description:
        "Chicken cubes, fresh ginger, garlic, honey, green chilli with marinated Nepali Style & spices",
      price: "8.95",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 18,
      title: "Naan",
      description: "White flour bread",
      price: "3.25",
      countInStock: 10,
      category: "appetizer",
      spice: [],
    },
    {
      id: 19,
      title: "Peshawari Naan",
      description: "White flour bread stuffed with dry fruits and Nuts",
      price: "4.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 20,
      title: '"Pudina Naan "',
      description: "White flour bread flavored with mint",
      price: "4.49",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 21,
      title: "Garlic Naan",
      description: "white flour bread flavored with Garlic",
      price: "4.49",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 22,
      title: "Basil Naan",
      description: "White flour bread flavored with fresh basil.",
      price: "3.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 23,
      title: "Hari Mirch Ka Naan",
      description: "White flour bread topped with green chillies.",
      price: "5.49",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 24,
      title: "Methi Ka Paratha",
      description: "Whole wheat bread stuffed with fenugreek leaf.",
      price: "4.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 25,
      title: "Chicken Naan",
      description: "White flour bread stuffed with minced chicken.",
      price: "5.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 26,
      title: "Tandoori Roti (Vegan)",
      description: "Whole wheat plain bread.",
      price: "3.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 27,
      title: "Onion Naan",
      description: "White flour bread stuffed with onion.",
      price: "4.49",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 28,
      title: "Alu Naan",
      description: "White flour bread stuffed with potato.",
      price: "4.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 29,
      title: "Lachha Paratha",
      description: "Layered whole wheat bread.",
      price: "4.49",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 30,
      title: "Rosemary Naan",
      description: "White flour bread flavored with rosemary.",
      price: "3.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 31,
      title: "Paneer Naan",
      description: "White flour bread stuffed with cheese.",
      price: "4.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 32,
      title: "Ekta Naan",
      description:
        "White flour bread stuffed with black sesame seed, dry fruits and nuts..",
      price: "5.49",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 33,
      title: "CHEESE NAAN",
      description: "White flour bread stuffed with mozzorolla cheese",
      price: "5.49",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 34,
      title: "Saag Aur Paneer",
      description:
        "Cheese cubes (paneer) cooked with light cream, spinach, onion and tomato sauce..",
      price: "14.99",
      countInStock: 10,
      category: "bread",
      spice: [],
    },
    {
      id: 35,
      title: "Dal Makhani",
      description: "Black lentil cooked with,cream, onion, omato and ginger.",
      price: "13.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 36,
      title: "Alu Gobi (vegan)",
      description: "Cauliflower, potato cooked with onion, tomato and herbs.",
      price: "13.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 37,
      title: "Masaladar Chhola (vegan)",
      description:
        "Chick Peas cooked with onion and tomato sauce, pomegranate seeds and roasted cumin seed.",
      price: "13.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 38,
      title: "Baigan Bharta (Vegan)",
      description:
        "Smoked eggplant cooked with fresh onion, tomato,green peas and chopped ginger.",
      price: "13.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 39,
      title: "Kadai Paneer",
      description:
        "Spicy. Cheese cubes (paneer) cooked with tomato sauce, fresh red and green peppers and onions.",
      price: "16.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 40,
      title: "Kachha Aam Ki Sabzi",
      description:
        "Mixed vegetables and raw mango cooked in creamy onion, tomato sauce with ginger, garlic and spices.",
      price: "16.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 41,
      title: "Kashmiri Aaloo Dam",
      description:
        "Stuffed potato cooked in onion sauce with creamy cashew paste,and dry fruits.",
      price: "16.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 42,
      title: "Paneer Malai Methi",
      description:
        "Cheese cubes(paneer) cooked with fenugreek leaf, onion tomato sauce and creamy cashew paste.",
      price: "16.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 43,
      title: "Ekta Dal (vegan)",
      description: "Yellow lentil cooked with onion and tomato",
      price: "13.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 44,
      title: "Mutter Paneer",
      description:
        "Cheese cubes(paneer) and peas cooked in onion tomato and creamy cashew sauce.",
      price: "14.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 45,
      title: "Paneer Tikka Masala",
      description:
        "Cheese cubes(paneer) cooked with creamy onion and tomato sauce.",
      price: "14.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 46,
      title: "Malai Kofta",
      description:
        "Cheese and potato dumplings cooked in a creamy cashew sauce, onion and tomato sauce with almond & raisin..",
      price: "14.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 47,
      title: "Navratna Curry",
      description:
        "Mixed vegetables cooked with creamy onion tomato & cashew sauce",
      price: "14.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 48,
      title: "Bhindi Masala  (Vegan)",
      description:
        "Okra cooked with onion, tomato sauce, chopped ginger and pomegranate seed.",
      price: "14.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 49,
      title: "EKTA Vegetables",
      description:
        "Fresh mixed vegetables,cheese cubes(Paneer) cooked with cream in fresh tomato & mustard Seed",
      price: "14.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 50,
      title: "Paneer Mangoli",
      description:
        "Cheese cubes(paneer)cooked in fresh mango, creamy onion and tomato sauce.",
      price: "16.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 51,
      title: "Shabanam Curry",
      description:
        "Mixed vegetables, cheese, peas, cooked with onion tomato in creamy cashew sauce.",
      price: "16.99",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 52,
      title: "Chicken Tikka Masala",
      description:
        "Boneless chicken breast cooked in creamy onion and tomato sauce.",
      price: "16.49",
      countInStock: 10,
      category: "vegetarian",
      spice: [],
    },
    {
      id: 53,
      title: "Chicken Curry",
      description:
        "Chicken breast cooked in onion tomato sauce (dhaba styles).",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 54,
      title: "Butter Chicken",
      description: "Chicken thigh cooked in a creamy tomato sauce.",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 55,
      title: "Kadai Chicken",
      description:
        "Spicy. Chicken breast cooked with tomato sauce, fresh green, and red peppers, and onion..",
      price: "16.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 56,
      title: "Mango Chicken",
      description:
        "Chicken breast cooked with fresh mango, onion and creamy tomato sauce moderately spiced.",
      price: "16.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 57,
      title: "Murg Goan Curry",
      description:
        "Chicken breast cooked with fresh coconut, onion & tomato sauce in light cream.",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 58,
      title: "Chicken Vindaloo",
      description: "Spicy. Chicken breast with hot onion & tomato sauce.",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 59,
      title: "Ekta Murg",
      description:
        "Chicken breast cooked with fresh tomato sauce & mustard seed in light cream.",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 60,
      title: "Chicken Korma",
      description:
        "Chicken breast cooked in onion tomato and creamy cashew sauce",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 61,
      title: "Chicken Saagwala",
      description:
        "Chicken breast cooked with spinach, onion tomato sauce & chopped ginger in light cream.",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 62,
      title: "Chicken Jalfrezi",
      description:
        "Chicken breast cooked with sliced red peppers, green peppers, onions in onion tomato sauce.",
      price: "16.49",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 63,
      title: "Lamb Vindaloo",
      description: "Spicy. Lamb cubes with hot onion & tomato sauce",
      price: "17.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 64,
      title: "Lamb Saagwala",
      description:
        "Lamb cubes cooked with spinach, onion, tomato sauce & chopped ginger in light cream",
      price: "17.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 65,
      title: "Lamb Chetinad",
      description:
        "Lamb cubes cooked with fresh coconut, curry leaves and mustard seed in a South Indian st",
      price: "17.99",
      countInStock: 10,
      category: "lamb",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 66,
      title: "Lamb Rogan Josh",
      description:
        "Traditional lamb curry from kashmir with onion and tomato sauce, in touch of yogurt",
      price: "17.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 67,
      title: "Kadai Lamb  .",
      description:
        "Spicy. Lamb cubes cooked with tomato sauce, fresh green, and red peppers, and onions.",
      price: "17.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 68,
      title: "Lamb Korma",
      description: "Lamb cubes cooked in onion tomato and creamy cashew sauce",
      price: "17.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 69,
      title: "Lamb Tikka Masala",
      description: "Lamb cubes cooked in a creamy onion and tomato sauce",
      price: "17.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 70,
      title: "Shrimp Tikka Masala",
      description: "Shrimp cooked in creamy onion and tomato sauce",
      price: "18.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 71,
      title: "Mango Shrimp",
      description:
        "Shrimp cooked with fresh mango, creamy onion tomato sauce moderately spiced",
      price: "18.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 72,
      title: "Goan Shrimp Curry",
      description:
        "Shrimp cooked with fresh coconut, onion and tomato sauce in light cream",
      price: "18.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 73,
      title: "Ekta Shrimp",
      description:
        "Shrimp cooked with fresh tomato sauce & mustard seed in light cream.",
      price: "18.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 74,
      title: "Goan Fish Curry",
      description:
        "Tilapia fish cooked with fresh coconut, onion & tomato sauce in light cream",
      price: "18.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 75,
      title: "Salmon Tikka Masala",
      description: "Salmon fish cooked in creamy onion and tomato sauce",
      price: "19.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 76,
      title: "Tandoori Chicken",
      description:
        "Chicken leg marinated with yogurt, ginger, garlic, and other Indian spices baked in tandoor oven",
      price: "15.99",
      countInStock: 10,
      category: "chicken",
      spice: ["Regular", "Mild", "Medium", "Spicy"],
    },
    {
      id: 77,
      title: "Boti Kabob",
      description:
        "Boneless lamb marinated overnight with ginger garlic and baked in tandoor oven",
      price: "17.99",
      countInStock: 10,
      category: "tandoor",
      spice: [],
    },
    {
      id: 78,
      title: "Mirch Tikka (Spicy)",
      description:
        "Chicken breast marinated in sour cream, green pepper, green chilies, and baked in tandoor oven",
      price: "16.99",
      countInStock: 10,
      category: "tandoor",
      spice: [],
    },
    {
      id: 79,
      title: "Ekta Kabob",
      description:
        "Chicken breast marinated in sour cream, ginger, garlic, spices baked in tandoor oven",
      price: "16.99",
      countInStock: 10,
      category: "tandoor",
      spice: [],
    },
    {
      id: 80,
      title: "Tandoori Shrimp",
      description:
        "Shrimp marinated in green chillies, chopped ginger, sour cream and cooked in tandoor oven.",
      price: "17.99",
      countInStock: 10,
      category: "seafood",
      spice: [],
    },
    {
      id: 81,
      title: "Tandoori Salmon",
      description: "",
      price: "19.99",
      countInStock: 10,
      category: "seafood",
      spice: [],
    },
    {
      id: 82,
      title: "Chicken Tikka",
      description:
        "Chicken Breast  marinated with yogurt, ginger, garlic and other Indian spices. Baked in a traditional clay oven and served with basmati rice.",
      price: "15.99",
      countInStock: 10,
      category: "tandoor",
      spice: [],
    },
    {
      id: 83,
      title: "Lamb Biryani",
      description: "",
      price: "17.99",
      countInStock: 10,
      category: "tandoor",
      spice: [],
    },
    {
      id: 84,
      title: "Chicken Biryani",
      description: "",
      price: "16.99",
      countInStock: 10,
      category: "biryani",
      spice: [],
    },
    {
      id: 85,
      title: "Ekta Biryani",
      description: "",
      price: "18.99",
      countInStock: 10,
      category: "biryani",
      spice: [],
    },
    {
      id: 86,
      title: "Shrimp Biryani",
      description: "",
      price: "18.99",
      countInStock: 10,
      category: "biryani",
      spice: [],
    },
    {
      id: 87,
      title: "Vegetable Biryani",
      description: "",
      price: "14.99",
      countInStock: 10,
      category: "biryani",
      spice: [],
    },
    {
      id: 88,
      title: "Papad",
      description: "",
      price: "2.49",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 89,
      title: "Mango Chutney",
      description: "",
      price: "2.99",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 90,
      title: "Plain Basmati Rice",
      description: "",
      price: "2.99",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 91,
      title: "Coconut Rice",
      description: "",
      price: "6.99",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 92,
      title: "Raita",
      description: "",
      price: "2.99",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 93,
      title: "Pickles",
      description: "",
      price: "2.99",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 94,
      title: "Onion Salad",
      description: "",
      price: "2.99",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 95,
      title: "Ekta Pulau",
      description: "",
      price: "5.99",
      countInStock: 10,
      category: "sideorder",
      spice: [],
    },
    {
      id: 96,
      title: "Gulab Jamun",
      description: "",
      price: "3.49",
      countInStock: 10,
      category: "deserts",
      spice: [],
    },
    {
      id: 97,
      title: "Rice Pudding",
      description: "",
      price: "3.49",
      countInStock: 10,
      category: "deserts",
      spice: [],
    },
    {
      id: 98,
      title: "Flavored Lassi",
      description:
        "(Yogurt base drink with choice of Strawberry, Guava, Mango, pomogranate, Sweet, Salt)",
      price: "3.99",
      countInStock: 10,
      category: "beverage",
      spice: ["Mango Lassi", "Strawberry Lassi"],
    },
    {
      id: 99,
      title: "Soda",
      description: "",
      price: "1.50",
      countInStock: 10,
      category: "beverage",
      spice: ["Coke", "Fanta", "Sprite"],
    },
    {
      id: 100,
      title: "Vegetables Madras Peppers",
      description:
        "An authentic Mixed Vegetable Curry ,delicious flavor of curry leaves ,dry red pepper,mustard seed with onion and tomato sauce.",
      price: "14.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 101,
      title: "Chicken Madras Peppers",
      description:
        "An authentic Chicken Curry, delicious flavor of curry leaves, dry red pepper, mustard seed with onion and tomato sauce.",
      price: "16.49",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 102,
      title: "Lamb Madras Peppers",
      description:
        "An authentic lamb Curry ,delicious flavor of curry leaves, dry red pepper, mustard seed with onion and tomato sauce.",
      price: "17.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 103,
      title: "Shrimp Madras Peppers",
      description:
        "An authentic Shrimp Curry ,delicious flavor of curry leaves, dry red pepper, mustard seed with onion and tomato sauce.",
      price: "18.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 104,
      title: "Paneer Madras Peppers",
      description:
        "An authentic Cheese cubes(Paneer) Curry ,delicious flavor of curry leaves ,dry red pepper,mustard seed with onion and tomato sauce.",
      price: "15.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 105,
      title: "Fish  Madras Peppers",
      description:
        "An authentic Fish(Talapia) Curry ,delicious flavor of curry leaves, dry red pepper, mustard seed with onion and tomato sauce.",
      price: "18.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 106,
      title: "Mulligatawny Soup",
      description: "Traditional soup with lental and vegetable",
      price: "4.95",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 107,
      title: "Spinach Soup",
      description: "Fresh Spinach, onion & garlic in a mint base",
      price: "4.95",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 108,
      title: "Tomato soup",
      description:
        "Freshly prepared tomato soup seasoned with herbs and spices",
      price: "4.95",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 109,
      title: "Vegetable Hakka Noodle",
      description:
        "Noodle with mix  vegetable, cabbage, onion, carrot, capsicums and scallion with Nepali style.",
      price: "10.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 110,
      title: "Chicken Hakka Noodle",
      description:
        "Noodle with mix  vegetable, cabbage, onion, carrot, capsicums, slice of chicken and eggs and scallion with Nepali style.",
      price: "12.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 111,
      title: "Vegetable MOMO",
      description:
        "Vegetable dumpling steam with touch of Nepali Love. Serve with peanut and sesame chutney.",
      price: "8.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 112,
      title: "Chicken MOMO",
      description:
        "Chicken dumpling steam with touch of Nepali Love. Serve with peanut and sesame chutney.",
      price: "10.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 113,
      title: "Fried Rice with Vegetable",
      description: "Rice Fried with Mix Vegetable.",
      price: "6.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
    {
      id: 114,
      title: "Chicken Fried Rice",
      description: "Rice Fried with Chicken and eggs.",
      price: "8.99",
      countInStock: 10,
      category: "",
      spice: [],
    },
  ],

  categories: [
    "all",
    "appetizer",
    "bread",
    "vegetarian",
    "chicken",
    "lamb",
    "seafood",
    "tandoor",
    "biryani",
    "sideorder",
    "beverage",
  ],
};

export default data;
